require("mappings.mappings")
require("settings.settings")
require("plugins.lazy")
require("plugins.colorscheme")
-- require("plugins.lunar-colorscheme")
require("plugins.plug-colorizer")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.mason")
require("plugins.lsp-config")
require("plugins.lsp-saga")
require("plugins.null-ls")
require("plugins.emmet-lsp")
require("mappings.lsp-maps")
require("mappings.luasnip-maps")
require("plugins.luasnip")
require("plugins.toggle-terminal")
require("plugins.indent")
require("plugins.illuminate")
require("plugins.impatient")
require("plugins.rest")
require("plugins.telescope")
require("plugins.project")
require("plugins.nvim-dap")
require("plugins.tabline")
require("plugins.comment")

-- require("plugins.packer")
